import sys
import re
import os
import json
import tempfile
import yt_dlp

def get_shortcode(url):
    pattern = r'/(?:p|reel|reels)/([A-Za-z0-9_\-]+)'
    match = re.search(pattern, url)
    return match.group(1) if match else None

def get_browser_cookies():
    try:
        import browser_cookie3
    except ImportError:
        sys.stderr.write("browser_cookie3 is not installed.\n")
        return None, None

    browsers = [
        ('chrome', browser_cookie3.chrome),
        ('firefox', browser_cookie3.firefox),
        ('edge', browser_cookie3.edge),
        ('opera', browser_cookie3.opera),
        ('brave', browser_cookie3.brave),
        ('safari', browser_cookie3.safari),
    ]

    for name, func in browsers:
        try:
            sys.stderr.write(f"Attempting to extract cookies from {name}...\n")
            cj = func(domain_name="instagram.com")
            if cj and len(cj) > 0:
                # Filter to only keep instagram.com cookies
                sys.stderr.write(f"Successfully loaded {len(cj)} cookies from {name}!\n")
                return cj, name
        except Exception as e:
            # Silence error for this browser and try next
            sys.stderr.write(f"Failed to load from {name}: {str(e)}\n")
            pass
    return None, None

def main():
    if len(sys.argv) < 2:
        print("RESULT:" + json.dumps({"error": "No URL provided"}))
        return

    url = sys.argv[1]
    shortcode = get_shortcode(url)
    if not shortcode:
        print("RESULT:" + json.dumps({"error": "Invalid URL. Could not parse shortcode."}))
        return

    session_id = os.environ.get('INSTAGRAM_SESSION_ID', '')
    cookie_file_path = None

    ydl_opts = {
        'quiet': True,
        'no_warnings': True,
        'skip_download': True,
        'extract_flat': False
    }

    # 1. First, check if session ID is configured in environment
    if session_id:
        sys.stderr.write("Using INSTAGRAM_SESSION_ID from environment.\n")
        try:
            fd, cookie_file_path = tempfile.mkstemp(suffix='.txt', prefix='ig-cookies-env-')
            os.close(fd)
            cookie_content = (
                "# Netscape HTTP Cookie File\n"
                "# Generated by InstAnalyst\n"
                f".instagram.com\tTRUE\t/\tTRUE\t0\tsessionid\t{session_id}\n"
            )
            with open(cookie_file_path, 'w', encoding='utf-8') as f:
                f.write(cookie_content)
            ydl_opts['cookiefile'] = cookie_file_path
        except Exception as e:
            sys.stderr.write(f"Failed to create temp cookie file from env: {str(e)}\n")
    else:
        # 2. Fall back to extracting cookies from local browsers
        sys.stderr.write("No INSTAGRAM_SESSION_ID in environment. Attempting browser cookie extraction...\n")
        cj, browser_name = get_browser_cookies()
        if cj:
            try:
                fd, cookie_file_path = tempfile.mkstemp(suffix='.txt', prefix=f'ig-cookies-{browser_name}-')
                os.close(fd)
                with open(cookie_file_path, 'w', encoding='utf-8') as f:
                    f.write("# Netscape HTTP Cookie File\n# Generated by InstAnalyst\n")
                    for cookie in cj:
                        secure_str = "TRUE" if cookie.secure else "FALSE"
                        domain = cookie.domain
                        domain_specified = "TRUE" if domain.startswith('.') else "FALSE"
                        expires = str(cookie.expires) if cookie.expires else "0"
                        path = cookie.path or "/"
                        f.write(f"{domain}\t{domain_specified}\t{path}\t{secure_str}\t{expires}\t{cookie.name}\t{cookie.value}\n")
                ydl_opts['cookiefile'] = cookie_file_path
                sys.stderr.write(f"Successfully configured cookiefile with cookies from: {browser_name}\n")
            except Exception as e:
                sys.stderr.write(f"Failed to create temp cookie file from browser: {str(e)}\n")
        else:
            sys.stderr.write("No browser cookies could be extracted. Proceeding anonymously.\n")

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            
            if not info:
                raise Exception("yt-dlp returned no metadata")

            # Check if it is a carousel/playlist
            if 'entries' in info and info['entries']:
                items = []
                for idx, entry in enumerate(info['entries']):
                    if entry:
                        items.append({
                            "id": idx + 1,
                            "thumbnail": entry.get('thumbnail') or entry.get('url'),
                            "downloadUrl": entry.get('url'),
                            "fileSize": "Unknown Size"
                        })
                
                result = {
                    "url": url,
                    "title": info.get('title') or f"Instagram Carousel {shortcode}",
                    "mediaType": "Carousel",
                    "isCarousel": True,
                    "items": items
                }
            else:
                dl_url = info.get('url')
                if not dl_url:
                    raise Exception("No download URL found in extracted info")
                
                ext = info.get('ext', '')
                inferred_type = "Video" if (ext == 'mp4' or 'mp4' in dl_url or 'video' in dl_url) else "Photo"
                
                # Determine final media type based on URL structure
                final_media_type = inferred_type
                if inferred_type == 'Video' and ('/reel/' in url or '/reels/' in url):
                    final_media_type = 'Reel'
                elif inferred_type == 'Video' and ('/stories/' in url or '/story/' in url):
                    final_media_type = 'Story'

                result = {
                    "url": url,
                    "title": info.get('title') or f"Instagram {final_media_type} {shortcode}",
                    "thumbnail": info.get('thumbnail') or dl_url,
                    "mediaType": final_media_type,
                    "isCarousel": False,
                    "fileSize": "Unknown Size",
                    "downloadUrl": dl_url
                }

            print("RESULT:" + json.dumps(result))

    except Exception as e:
        err_msg = str(e)
        if "empty media response" in err_msg or "login" in err_msg or "cookie" in err_msg:
            print("RESULT:" + json.dumps({
                "error": "AUTH_REQUIRED",
                "message": "Instagram authentication is required. Please ensure you are logged into Instagram in your web browser (Chrome, Firefox, or Edge) or configure INSTAGRAM_SESSION_ID in backend/.env"
            }))
        else:
            print("RESULT:" + json.dumps({
                "error": "DOWNLOAD_FAILED",
                "message": err_msg
            }))
    finally:
        # Clean up temp cookie file
        if cookie_file_path and os.path.exists(cookie_file_path):
            try:
                os.remove(cookie_file_path)
            except Exception:
                pass

if __name__ == "__main__":
    main()
